#!/usr/bin/env bash
# Display information about subdomains.

printer ()
{
        if dig "$2.$1" | grep -A1 'ANSWER SECTION:' > file.txt
        then
                # echo "Dig passed!."
                var="$?"
        else
                echo "DID STH BAD!"
        fi
        if ! awk -v var="$2" 'NR==2 {print "The subdomain "var" is a "$4" record and points to "$NF}' file.txt
        then
                echo "Awks it!!!"
                if [ "$var" -ne 0 ]
                then
                        echo "The Hell!!!"
                fi
        fi
}

if [ "${2+defined}" ]
then
        printer $1 $2
else
        printer $1 "www"  
        printer $1 "lb-01"
        printer $1 "web-01"
        printer $1 "web-02"
fi
