#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 13352-web-01 54.152.32.239:80 check\n\tserver 13352-web-02 54.209.120.47:80 check\n' /etc/haproxy/haproxy.cfg
if haproxy -f /etc/haproxy/haproxy.cfg -c;
then
  service haproxy restart
fi
