#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
# Add HAProxy PPA
apt update
apt install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
apt install haproxy=2.6\* && apt install vim-haproxy haproxy-doc

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\n\tbalance roundrobin\n\toption httpchk GET \/ \n\tserver 13352-web-01 34.238.194.35:80 check\n\tserver 13352-web-02 35.175.63.49:80 check\n' /etc/haproxy/haproxy.cfg
if haproxy -f /etc/haproxy/haproxy.cfg -c;
then
  service haproxy restart
fi
