#!/usr/bin/env bash
# Change nginx listening ports to 8080 and run it as nginx user.
chmod 204 /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
pkill -f apache2
sudo -u nginx service nginx start
