#!/usr/bin/env bash
# Change nginx listening ports to 8080 and run it as nginx user.
sed -i '1 s/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
service nginx reload
